id = "auto-header"
name = "Auto File Header"
description = "Automatically inserts file headers (Copyright, Author, Date) when creating new empty files. Requires .auto-header.toml config file."
version = "0.1.3"
schema_version = 1
authors = ["MrAMS <2421653893@qq.com>"]
repository = "https://github.com/MrAMS/zed-auto-file-header"

# Language server for auto file headers
# Supports most common programming languages
[language_servers.auto-header]
name = "Auto Header"
languages = [
    "C", "C++", "Rust", "Go", "JavaScript", "TypeScript", "Python", 
    "Java", "Kotlin", "Swift", "Objective-C", "C#", "Scala",
    "Ruby", "Perl", "PHP", "Shell Script", "Bash", 
    "HTML", "CSS", "SCSS", "Less", "YAML", "JSON", "TOML",
    "Markdown", "SQL", "Lua", "Haskell", "Elixir", "Erlang",
    "Clojure", "Lisp", "Scheme", "R", "Julia", "Vim Script"
]



