[workspace]
members = ["extension", "server"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["MrAMS <2421653893@qq.com>"]
license = "MIT"
repository = "https://github.com/MrAMS/zed-auto-file-header"
