[package]
name = "auto-header-extension"
version = "0.2.5"
edition = "2021"
authors = ["MrAMS <2421653893@qq.com>"]
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
